# Generated by Django 5.1.5 on 2025-03-31 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0016_alter_workorder_planed_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_range',
            field=models.CharField(default='P', max_length=200, verbose_name='作業範囲'),
        ),
    ]
