# Generated by Django 5.1.5 on 2025-04-08 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0019_alter_workorder_process_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='process_pattern',
            field=models.CharField(choices=[('No.1', 'No.1'), ('No.2', 'No.2'), ('No.3', 'No.3'), ('No.4', 'No.4'), ('一般工程', '一般工程'), ('その他', 'その他')], default='No.1', max_length=10, verbose_name='製造工程パタン'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_group',
            field=models.CharField(choices=[('牛久工場', '牛久工場'), ('千葉工場', '千葉工場'), ('石下工場', '石下工場'), ('その他', 'その他')], default='牛久工場', max_length=10, verbose_name='製作グループ'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('FB', 'FB'), ('PL', 'PL')], default='FB', max_length=2, verbose_name='作業種別'),
        ),
    ]
