# Generated by Django 5.2 on 2025-04-13 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0020_alter_workorder_process_pattern_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_type',
            field=models.CharField(choices=[('FB', 'FB'), ('PL', 'PL')], default='FB', max_length=2, verbose_name=''),
        ),
    ]
