# Generated by Django 5.2 on 2025-04-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0021_alter_workorder_work_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='release_date',
            field=models.DateField(auto_now_add=True, verbose_name='発行日'),
        ),
    ]
