# Generated by Django 5.2 on 2025-11-25 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyoshiji', '0022_alter_workorder_release_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='work_hours',
            field=models.DecimalField(decimal_places=1, max_digits=5, verbose_name='作業工数時間'),
        ),
    ]
