# Generated by Django 5.2 on 2025-05-09 13:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sagyodenpyo', '0006_alter_worklog_work_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worklog',
            name='work_hours',
            field=models.DecimalField(decimal_places=0, default='', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)], verbose_name='時間'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_minute',
            field=models.DecimalField(decimal_places=0, default='', max_digits=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(59)], verbose_name='分'),
        ),
        migrations.AlterField(
            model_name='worklog',
            name='work_trenum',
            field=models.CharField(default='', max_length=3, verbose_name='枝番'),
        ),
    ]
